language: php
sudo: false
php:
- 5.4
- 5.5
- 5.6
- 7.0
matrix:
  fast_finish: true
  allow_failures:
  - env: MAGENTO_VERSION=magento-ce-1.9.1.1
  - env: MAGENTO_VERSION=magento-ce-1.9.1.0
  - php: 5.4
    env: MAGENTO_VERSION=magento-ce-1.9.2.2
  - php: 5.4
    env: MAGENTO_VERSION=magento-ce-1.9.2.1
  - php: 5.4
    env: MAGENTO_VERSION=magento-ce-1.9.2.0
  - php: 5.6
    env: MAGENTO_VERSION=magento-mirror-1.8.1.0
  - php: 7.0
    env: MAGENTO_VERSION=magento-mirror-1.8.1.0
env:
  global:
  - APPNAME=Ffuenf_GoogleAnalyticsPlus
  - secure: BJDqc4eEwvwQE3tKiD9Y8947MtyxoF3zI5nzgV+THkCdaT79B3A9tkHoH5ZX7s8fvjCf5umarsxSOe7rTmjdf12YiKNhuhqJZDCXghwsQ6C75/8cUcvQCTSQk/QsQrpkilaGUUH8eoi/64CHkefiI8fGbF0IaRDZRuADi4plvUBJ4kHyCOuwiroVlm6ZD2WRD7kT41Ako3VRV82kBy0MeZQ8Wh2TUjNVuuTNUKLAIx7ST20nFDOo+xH5LelKrlHhYCzt/6B7fpnuC9yhMYJDW7MHh8jb7wCPlxAuB9uI0PAH1p79cjusJMsEa/bkJSQyu+rm8sn3a1KGYpqjFJIebe6M69xDE+h0PkKNcidMe87B3dgVdCJu4qGSh4d41SeKc7DBQvao/Xhxz/PkPijZeYCTN1irnWpad2yd+Mqqk91EcgpWcYbzxai2u34+NyuGl6chyyFfjM0Fu9ZYSBDt89EfAd/Meuby0gLQ5XKAQFt/b6EpBTh4W3dXjO0beCo+nH2dZw63NtU/CdsuZIi1EZ3VXbQVayoh1dsBoHcPX7601fBlAXYDVx9PpEpSFZh/5g3qeCTiELwpj87mhWnirXNKA7KNJN4z6A4/n4faLMutJO9DJS1z/nuqASYjmT/ht3+4HePt1U6YV9Q1XLhc6UlODyEc4Aqgh2a7V1g8uac=
  - secure: BGEOq4NLOPon0m8n5fTFZ986Rx2kkwdiecLBO5ZaNbTYCgsDyLPjulKY81QqFFpEyQgopRyI21JXn86x6tI3j1JDq0SQLknWc8wrX7+8ZDNLXVi8rAuWLqHBQAwd3f1WNF9Df0CFrRdetDW4LbkEQMfyOGfegKixLeVUmZRSpWi2ZjuTGvTDyQW7HOtOLNuLly1maEltQ8TxC2CMxoyZ54X88xSiWgSZiwFn2KreyNNUmdAC4iRVGLXcBlcUTviWqfvxtfzYJGf1YzElmkiPSeki1rfMGBU/R29u3QOlmCzApyYTdPRwbJlLJk5L+xKYRqTdFacJOR1d9353PTds5a1bI7s1cNZQnGhJONWLoniueD2qe5mDvFTCgjHEkqDZkLN7Un3Fu/TSGUCGg2dsKsZzhOKTGhFhqzF0Np8AVoBmrGfT8FGsUfxal23752F7+dRmWK8T6QnB97OCsAMoze7VCBhmXYgsC+Ccf5pPJmFYwzKAuv+yyTq4df8MS1VNnd5uNBeMsFUp8CeUsxhY2C6YGYXPMeYSkFdMSnYzBywYKHKf/zRnOg5Gj6KRQnYjsaK+Ai0hEQroeG7PV7tlmSLn9OXsLSWqTRCPCiZZIj0CRlOEpEgwBn2Kc0ajPp/mHTNljsvC5/j8G8CKmrTwY5SdPJHFauXlT+LoptJPiHc=
  matrix:
  - MAGENTO_VERSION=magento-ce-1.9.2.2
  - MAGENTO_VERSION=magento-ce-1.9.1.1
  - MAGENTO_VERSION=magento-mirror-1.8.1.0
  - MAGENTO_VERSION=magento-mirror-1.7.0.2
  - MAGENTO_VERSION=magento-mirror-1.6.2.0
before_script:
- composer self-update
- composer install --prefer-source
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/setup.sh
  | bash
before_deploy:
- gem install mime-types -v 2.6.2
deploy:
  provider: releases
  file:
  - "${APPNAME}-${TRAVIS_TAG}.zip"
  - "${APPNAME}-${TRAVIS_TAG}.tar.gz"
  skip_cleanup: true
  on:
    branch: master
    tags: true
  api_key:
    secure: ba2eyxxSQ3rlsSop/IJ9xzPOa6AcZa4FUlvmsa/NDdr0afrham8KDpjKKac4hZmKnOW8876EVvUun75EeHPt0+0lW3otrWQ5CJMrz0xponn6XHxIPNbNoxe+Dsr33GxcXdVouw5Ka0TE4hxZf8yIcGlC3qkb3UFfh0T8xEyqxhRQOEOW0ytINDp9lX6z2LafIrNb2pEGGD7ZaJXxNELIW0268FTWvZeonBNguP76HXQsb/HrDwEsnxigqhsHYTdGhgep7fAj0tADFGyh3BDb8dPbXj8zSOY1zUz7e5S0/UmdjBySJ5IcUnGO+FbZotdC3kVzZRmuKiDVbZSusJtZQFL+AQQBz52wILpHgNYQT4Rx0aRPR8WNc1wUF3wobTrNgLQ0Z6pzusCdxB+Ks2LBdyE+VfC5b+vL0UbxweBGjPnLimAugIsywkA8EtiC5DAgAMJNz+j+FA3C8GB6R8bDtzXZHcurDdXo1zijbBX4vJKRHvZnY7WfgUnqYRegSaty1zDfoAxGtQ0qTcrvkg322CSNdWGTRyiPjD2XeDLrWk/oSxq0ewDVQRKak81d4xt9dsiQjmY8O+xH77nclLnLbHfXRWX60iqtuhuf3Lgo/cxA0xJkDit/gD5+6lep6ZckrNHQ5JA+9av//5gwBZkpFhcWxwZTTiXBWR3Fb33vw6w=
notifications:
  slack:
    secure: NMmIViwZuqdDKhatdpHTxomcwYVYy7N+mquciqWN3/ufpYgetjJTP9H2uM0lSiIBOYttyDnvvaSduABYoly5MsMWxudfdIVKFIbIsKp/aIJyXfUK4PrGPFrs4026IacjKjSR8S1mkOXbGld2La7do29U8O6quxAb9WIHlzkUIRnWoeWde+Wpb8mQH5kRSOngPdfxKDdKi5UEoSucQPXECU2qle7r9nwG2iV6pxeH5J5mvVhvub54377H6bbuhI+tIRTo0HZx+JAJk0Hnk5LuuMSRhvLMGblg+VK5/NgdkzjbUdsz7233NaMEXhc1l5qczXOs+9dpDybhFgajv6coJbVyTWJGWrHGfiPciBbS3jmcxnzMDIdUUKfVOn2z+/TF+XMKeNb9LziPxgCYb4n8VsEfNLv4ENfpFFpvgeqPcdxwDN8ECZP1TFXtsknQRtk312QZ6d+JvxtyvP4mNWCOtxjYw6bqAwAhKemNG81crw41inTbPV/vGipan8NfX09bk+WFLjjR1ggxVk5hLirjmLgBOVSm3ICaDy3LtIX9AaExl/EIog0+S96TsfuAHypaINyFljbdNo0t0l7R19yKl/mq3hUg0QrLM4hyQCZn4KQw0uGj01RXTuh+/Ck8g51W+w1XqPrAy/0mDYWi+QGFGo/CTTi5eEkHAyUwhiyVbl0=
